CREATE TABLE Users (
  userID VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  role ENUM('Admin', 'Doctor', 'Nurse', 'LabTechnician') NOT NULL
);

CREATE TABLE AuditTrail (
  auditID VARCHAR(36) PRIMARY KEY,
  userID VARCHAR(36),
  action VARCHAR(255),
  timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES Users(userID)
);